# Generated by Django 3.0.2 on 2020-01-17 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=64)),
                ('cust_phone', models.IntegerField()),
                ('cust_email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person_name', models.CharField(max_length=64)),
                ('delivery_person_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='fos.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustOrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('estimated_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order_status', models.CharField(max_length=64)),
                ('order_address', models.CharField(max_length=64)),
                ('bill_amount', models.IntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_id', to='fos.CustomerDetails')),
                ('delivery_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_id', to='fos.DeliveryPerson')),
            ],
        ),
        migrations.CreateModel(
            name='CustOrderSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.IntegerField()),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_id', to='fos.FoodDetails')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='fos.CustOrderStatus')),
            ],
        ),
    ]
