# Generated by Django 3.0.2 on 2020-01-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'verbose_name_plural': 'Customer Details'},
        ),
        migrations.AlterModelOptions(
            name='custorderselection',
            options={'verbose_name_plural': 'Customer Order Selection'},
        ),
        migrations.AlterModelOptions(
            name='custorderstatus',
            options={'verbose_name_plural': 'Customer Order Status'},
        ),
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'verbose_name_plural': 'Delivery Person'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food Category'},
        ),
        migrations.AlterModelOptions(
            name='fooddetails',
            options={'verbose_name_plural': 'Food Details'},
        ),
        migrations.AlterField(
            model_name='fooddetails',
            name='food_name',
            field=models.CharField(max_length=64),
        ),
    ]
