# Generated by Django 3.0.2 on 2020-01-24 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0002_auto_20200124_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorderstatus',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='estimated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
