# Generated by Django 3.0.2 on 2020-01-24 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0003_auto_20200124_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorderstatus',
            name='bill_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='estimated_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
