# Generated by Django 3.0.2 on 2020-01-24 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0005_auto_20200124_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorderstatus',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='estimated_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
