# Generated by Django 3.0.2 on 2020-01-24 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fos', '0006_auto_20200124_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorderstatus',
            name='checkout_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='estimated_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='order_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='custorderstatus',
            name='order_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
